Trf 2.4
DoeVida/HemoLink pull request #79
Opened 2024-09-26 01:31 UTC by Barbaravazz

Corrigido o mapeamento da classe papel

2024-09-27 18:59 UTC, marianaacb requested changes
- remover a palavra chave `void `dos construtores

2024-09-27 18:59 UTC, marianaacb commented on src/main/java/br/senac/hemolink/modelo/entidade/papel/Papel.java
> +import javax.persistence.JoinColumn;
remover linha 8 (não está sendo usada)

2024-09-27 18:59 UTC, marianaacb commented on src/main/java/br/senac/hemolink/modelo/entidade/papel/Papel.java
> +
adicionar entre as linhas 13 e 14:
`private static final long serialVersionUID = 1L;`

2024-10-07 17:24 UTC, DoeVida approved these changes

2024-10-07 17:31 UTC, marianaacb approved these changes

2024-10-07 17:33 UTC, merged